// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-xMkwcl7tYuAvZ51Jh5u8K9otMZn34I',
    appId: '1:1029376016626:web:47e4b87d21ede45033d06b',
    messagingSenderId: '1029376016626',
    projectId: 'house-construction-tracker',
    authDomain: 'house-construction-tracker.firebaseapp.com',
    storageBucket: 'house-construction-tracker.firebasestorage.app',
    measurementId: 'G-VHZR4NT68Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN6eeDTU6rR28TLxGhO5Iz3mNO0hvwfZ0',
    appId: '1:1029376016626:android:ebc3edce594a6f6033d06b',
    messagingSenderId: '1029376016626',
    projectId: 'house-construction-tracker',
    storageBucket: 'house-construction-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-BaoNS-jD58Lei6oQmUsZJ5mETCLTMsA',
    appId: '1:1029376016626:ios:cf64736a545fe10633d06b',
    messagingSenderId: '1029376016626',
    projectId: 'house-construction-tracker',
    storageBucket: 'house-construction-tracker.firebasestorage.app',
    iosBundleId: 'com.example.newHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-BaoNS-jD58Lei6oQmUsZJ5mETCLTMsA',
    appId: '1:1029376016626:ios:cf64736a545fe10633d06b',
    messagingSenderId: '1029376016626',
    projectId: 'house-construction-tracker',
    storageBucket: 'house-construction-tracker.firebasestorage.app',
    iosBundleId: 'com.example.newHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-xMkwcl7tYuAvZ51Jh5u8K9otMZn34I',
    appId: '1:1029376016626:web:5428994e8bb803d233d06b',
    messagingSenderId: '1029376016626',
    projectId: 'house-construction-tracker',
    authDomain: 'house-construction-tracker.firebaseapp.com',
    storageBucket: 'house-construction-tracker.firebasestorage.app',
    measurementId: 'G-3HRTZMCM95',
  );

}